//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34003
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Controls.DataVisualization.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Windows.Controls.DataVisualization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Changing the Chart&apos;s Axes property is not supported; changes to the collection should be made with its .Add/.Remove methods instead. 的本地化字符串。
        /// </summary>
        internal static string Chart_Axes_SetterNotSupported {
            get {
                return ResourceManager.GetString("Chart_Axes_SetterNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Axis location cannot be changed to auto when hosted inside of a series host. 的本地化字符串。
        /// </summary>
        internal static string Chart_AxisLocationChanged_CantBeChangedToAutoWhenHostedInsideOfASeriesHost {
            get {
                return ResourceManager.GetString("Chart_AxisLocationChanged_CantBeChangedToAutoWhenHostedInsideOfASeriesHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changing the Chart&apos;s Series property is not supported; changes to the collection should be made with its .Add/.Remove methods instead. 的本地化字符串。
        /// </summary>
        internal static string Chart_Series_SetterNotSupported {
            get {
                return ResourceManager.GetString("Chart_Series_SetterNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The content property must be set to a Chart object. 的本地化字符串。
        /// </summary>
        internal static string DataPointSeriesDropTarget_set_Content_ContentMustBeAChart {
            get {
                return ResourceManager.GetString("DataPointSeriesDropTarget_set_Content_ContentMustBeAChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assigned dependent axis cannot be used. This may be due to an unset Orientation property for the axis or a type mismatch between the values being plotted and those supported by the axis. 的本地化字符串。
        /// </summary>
        internal static string DataPointSeriesWithAxes_GetAxes_AssignedDependentAxisCannotBeUsed {
            get {
                return ResourceManager.GetString("DataPointSeriesWithAxes_GetAxes_AssignedDependentAxisCannotBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assigned independent axis cannot be used. This may be due to an unset Orientation property for the axis. 的本地化字符串。
        /// </summary>
        internal static string DataPointSeriesWithAxes_GetAxes_AssignedIndependentAxisCannotBeUsed {
            get {
                return ResourceManager.GetString("DataPointSeriesWithAxes_GetAxes_AssignedIndependentAxisCannotBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No suitable axis is available for plotting the dependent value. 的本地化字符串。
        /// </summary>
        internal static string DataPointSeriesWithAxes_NoSuitableAxisAvailableForPlottingDependentValue {
            get {
                return ResourceManager.GetString("DataPointSeriesWithAxes_NoSuitableAxisAvailableForPlottingDependentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This series does not support radial axes. 的本地化字符串。
        /// </summary>
        internal static string DataPointSeriesWithAxes_ThisSeriesDoesNotSupportRadialAxes {
            get {
                return ResourceManager.GetString("DataPointSeriesWithAxes_ThisSeriesDoesNotSupportRadialAxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot determine the size of an axis without an orientation. 的本地化字符串。
        /// </summary>
        internal static string DisplayAxis_GetLength_CannotDetermineTheLengthOfAnAxisWithAnOrientationOfNone {
            get {
                return ResourceManager.GetString("DisplayAxis_GetLength_CannotDetermineTheLengthOfAnAxisWithAnOrientationOfNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attempt to set Edge property to an invalid value. 的本地化字符串。
        /// </summary>
        internal static string EdgePanel_OnEdgePropertyChanged {
            get {
                return ResourceManager.GetString("EdgePanel_OnEdgePropertyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The DataRangeBinding property of the Interpolator must be bound to an IConvertible object. 的本地化字符串。
        /// </summary>
        internal static string Interpolator_IncludeInRange_DataRangeBindingNotIConvertible {
            get {
                return ResourceManager.GetString("Interpolator_IncludeInRange_DataRangeBindingNotIConvertible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The maximum value must be larger than or equal to the minimum value. 的本地化字符串。
        /// </summary>
        internal static string Range_ctor_MaximumValueMustBeLargerThanOrEqualToMinimumValue {
            get {
                return ResourceManager.GetString("Range_ctor_MaximumValueMustBeLargerThanOrEqualToMinimumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;Cannot read the Maximum of an empty range.&quot; 的本地化字符串。
        /// </summary>
        internal static string Range_get_Maximum_CannotReadTheMaximumOfAnEmptyRange {
            get {
                return ResourceManager.GetString("Range_get_Maximum_CannotReadTheMaximumOfAnEmptyRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;Cannot read the Minimum of an empty range.&quot; 的本地化字符串。
        /// </summary>
        internal static string Range_get_Minimum_CannotReadTheMinimumOfAnEmptyRange {
            get {
                return ResourceManager.GetString("Range_get_Minimum_CannotReadTheMinimumOfAnEmptyRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0},{1}] 的本地化字符串。
        /// </summary>
        internal static string Range_ToString_Data {
            get {
                return ResourceManager.GetString("Range_ToString_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Data. 的本地化字符串。
        /// </summary>
        internal static string Range_ToString_NoData {
            get {
                return ResourceManager.GetString("Range_ToString_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The maximum value must be larger than or equal to the minimum value. 的本地化字符串。
        /// </summary>
        internal static string RangeAxis_MaximumValueMustBeLargerThanOrEqualToMinimumValue {
            get {
                return ResourceManager.GetString("RangeAxis_MaximumValueMustBeLargerThanOrEqualToMinimumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The minimum value must be smaller than or equal to the maximum value. 的本地化字符串。
        /// </summary>
        internal static string RangeAxis_MinimumValueMustBeLargerThanOrEqualToMaximumValue {
            get {
                return ResourceManager.GetString("RangeAxis_MinimumValueMustBeLargerThanOrEqualToMaximumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collection is read-only. 的本地化字符串。
        /// </summary>
        internal static string ReadOnlyObservableCollection_CollectionIsReadOnly {
            get {
                return ResourceManager.GetString("ReadOnlyObservableCollection_CollectionIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot reset a ResourceDictionaryEnumerator; reset the ResourceDictionaryDispenser instead. 的本地化字符串。
        /// </summary>
        internal static string ResourceDictionaryEnumerator_CantResetEnumeratorResetDispenserInstead {
            get {
                return ResourceManager.GetString("ResourceDictionaryEnumerator_CantResetEnumeratorResetDispenserInstead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Series {0} 的本地化字符串。
        /// </summary>
        internal static string Series_OnGlobalSeriesIndexPropertyChanged_UntitledSeriesFormatString {
            get {
                return ResourceManager.GetString("Series_OnGlobalSeriesIndexPropertyChanged_UntitledSeriesFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A series cannot be added to more than one series host. 的本地化字符串。
        /// </summary>
        internal static string Series_SeriesHost_SeriesHostPropertyNotNull {
            get {
                return ResourceManager.GetString("Series_SeriesHost_SeriesHostPropertyNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid attempt to remove permanent axis from axis collection. 的本地化字符串。
        /// </summary>
        internal static string SeriesHostAxesCollection_InvalidAttemptToRemovePermanentAxisFromSeriesHost {
            get {
                return ResourceManager.GetString("SeriesHostAxesCollection_InvalidAttemptToRemovePermanentAxisFromSeriesHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An axis cannot be removed from a series host when one or more hosted series is listening to it. 的本地化字符串。
        /// </summary>
        internal static string SeriesHostAxesCollection_RemoveItem_AxisCannotBeRemovedFromASeriesHostWhenOneOrMoreSeriesAreListeningToIt {
            get {
                return ResourceManager.GetString("SeriesHostAxesCollection_RemoveItem_AxisCannotBeRemovedFromASeriesHostWhenOneOrMo" +
                        "reSeriesAreListeningToIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Either ItemTemplate must be set or TreeMapItemDefinitionSelector must return a non-null template. 的本地化字符串。
        /// </summary>
        internal static string TreeMap_BuildTreeMapTree_TemplateNotSet {
            get {
                return ResourceManager.GetString("TreeMap_BuildTreeMapTree_TemplateNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value of PropertyBinding property of an interpolator cannot be null. 的本地化字符串。
        /// </summary>
        internal static string TreeMap_CreateChildren_InterpolatorBindingNotSet {
            get {
                return ResourceManager.GetString("TreeMap_CreateChildren_InterpolatorBindingNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changing the TreeMap&apos;s Interpolators Property is not supported; changes to the collection should be made with its .Add/.Remove methods instead. 的本地化字符串。
        /// </summary>
        internal static string TreeMap_Interpolators_SetterNotSupported {
            get {
                return ResourceManager.GetString("TreeMap_Interpolators_SetterNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid attempt to insert a duplicate item. 的本地化字符串。
        /// </summary>
        internal static string UniqueObservableCollection_InvalidAttemptToInsertADuplicateItem {
            get {
                return ResourceManager.GetString("UniqueObservableCollection_InvalidAttemptToInsertADuplicateItem", resourceCulture);
            }
        }
    }
}
