//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34003
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Windows.Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The modification made to the collection lead to an invalid Selection state. Please check the SelectionMode to allow zero or multiple items. 的本地化字符串。
        /// </summary>
        internal static string Accordion_InvalidManipulationOfSelectionCollections {
            get {
                return ResourceManager.GetString("Accordion_InvalidManipulationOfSelectionCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Should not signal a finish when item is not expected to perform an action. 的本地化字符串。
        /// </summary>
        internal static string Accordion_OnActionFinish_InvalidFinish {
            get {
                return ResourceManager.GetString("Accordion_OnActionFinish_InvalidFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid ExpandDirection value &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Accordion_OnExpandDirectionPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Accordion_OnExpandDirectionPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot set read-only property SelectedIndices. 的本地化字符串。
        /// </summary>
        internal static string Accordion_OnSelectedIndicesChanged_InvalidWrite {
            get {
                return ResourceManager.GetString("Accordion_OnSelectedIndicesChanged_InvalidWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot set read-only property SelectedItems. 的本地化字符串。
        /// </summary>
        internal static string Accordion_OnSelectedItemsChanged_InvalidWrite {
            get {
                return ResourceManager.GetString("Accordion_OnSelectedItemsChanged_InvalidWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid SelectionMode value &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Accordion_OnSelectionModePropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Accordion_OnSelectionModePropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid SelectionSequence value &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Accordion_OnSelectionSequencepropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Accordion_OnSelectionSequencepropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported collection action &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Accordion_UnsupportedCollectionAction {
            get {
                return ResourceManager.GetString("Accordion_UnsupportedCollectionAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ContentTargetSize is a read-only value and is set through Accordion. 的本地化字符串。
        /// </summary>
        internal static string AccordionItem_InvalidWriteToContentTargetSize {
            get {
                return ResourceManager.GetString("AccordionItem_InvalidWriteToContentTargetSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExpandDirection is a read-only value and is set through Accordion. 的本地化字符串。
        /// </summary>
        internal static string AccordionItem_InvalidWriteToExpandDirection {
            get {
                return ResourceManager.GetString("AccordionItem_InvalidWriteToExpandDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot modify the IsSelected property while item is locked. 的本地化字符串。
        /// </summary>
        internal static string AccordionItem_OnIsSelectedPropertyChanged_InvalidChange {
            get {
                return ResourceManager.GetString("AccordionItem_OnIsSelectedPropertyChanged_InvalidChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Action &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string AccordionItem_StartAction_InvalidAction {
            get {
                return ResourceManager.GetString("AccordionItem_StartAction_InvalidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot start an action when there is no action scheduled. 的本地化字符串。
        /// </summary>
        internal static string AccordionItem_StartAction_InvalidCall {
            get {
                return ResourceManager.GetString("AccordionItem_StartAction_InvalidCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot perform operation. 的本地化字符串。
        /// </summary>
        internal static string Automation_OperationCannotBePerformed {
            get {
                return ResourceManager.GetString("Automation_OperationCannotBePerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid ExpandDirection value &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Expander_OnExpandDirectionPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Expander_OnExpandDirectionPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transition &apos;{0}&apos; was not defined. 的本地化字符串。
        /// </summary>
        internal static string TransitioningContentControl_TransitionNotFound {
            get {
                return ResourceManager.GetString("TransitioningContentControl_TransitionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsTransitioning property is read-only. 的本地化字符串。
        /// </summary>
        internal static string TransitiotioningContentControl_IsTransitioningReadOnly {
            get {
                return ResourceManager.GetString("TransitiotioningContentControl_IsTransitioningReadOnly", resourceCulture);
            }
        }
    }
}
