//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34003
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Windows.Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid FilterMode enumeration value. The value must be one of the defined AutoCompleteFilterMode values to be accepted. 的本地化字符串。
        /// </summary>
        internal static string AutoComplete_OnFilterModePropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("AutoComplete_OnFilterModePropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid maximum drop down height value &apos;{0}&apos;. The value must be greater than or equal to zero. 的本地化字符串。
        /// </summary>
        internal static string AutoComplete_OnMaxDropDownHeightPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("AutoComplete_OnMaxDropDownHeightPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid MinimumPopulateDelay value &apos;{0}&apos;. The value must be greater than or equal to zero. 的本地化字符串。
        /// </summary>
        internal static string AutoComplete_OnMinimumPopulateDelayPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("AutoComplete_OnMinimumPopulateDelayPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot set read-only property SearchText. 的本地化字符串。
        /// </summary>
        internal static string AutoComplete_OnSearchTextPropertyChanged_InvalidWrite {
            get {
                return ResourceManager.GetString("AutoComplete_OnSearchTextPropertyChanged_InvalidWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot perform operation. 的本地化字符串。
        /// </summary>
        internal static string Automation_OperationCannotBePerformed {
            get {
                return ResourceManager.GetString("Automation_OperationCannotBePerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid index value &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string DomainUpDown_CurrentIndex_InvalidValue {
            get {
                return ResourceManager.GetString("DomainUpDown_CurrentIndex_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid InvalidInputAction value &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string DomainUpDown_InvalidInputAction_InvalidValue {
            get {
                return ResourceManager.GetString("DomainUpDown_InvalidInputAction_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid ExpandDirection value &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Expander_OnExpandDirectionPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Expander_OnExpandDirectionPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid attempt to change read-only property &quot;{0}.&quot; 的本地化字符串。
        /// </summary>
        internal static string InvalidAttemptToChangeReadOnlyProperty {
            get {
                return ResourceManager.GetString("InvalidAttemptToChangeReadOnlyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot set read-only property TimeItemsSelection. 的本地化字符串。
        /// </summary>
        internal static string ListTimePickerPopup_TimeItemsSelection_ReadOnly {
            get {
                return ResourceManager.GetString("ListTimePickerPopup_TimeItemsSelection_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid double value &apos;{0}&apos;: valid value is of double type and within decimal range. 的本地化字符串。
        /// </summary>
        internal static string NumericUpDown_EnsureValidDoubleValue_InvalidDoubleValue {
            get {
                return ResourceManager.GetString("NumericUpDown_EnsureValidDoubleValue_InvalidDoubleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Increment value &apos;{0}&apos;: valid value is of double type, within decimal range, and positive 的本地化字符串。
        /// </summary>
        internal static string NumericUpDown_EnsureValidIncrementValue_InvalidValue {
            get {
                return ResourceManager.GetString("NumericUpDown_EnsureValidIncrementValue_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid DecimalPlaces value &apos;{0}&apos;: valid value is of int type and within 0 and 15 inclusive. 的本地化字符串。
        /// </summary>
        internal static string NumericUpDown_OnDecimalPlacesPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("NumericUpDown_OnDecimalPlacesPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The collection is currently ReadOnly and should not be modified. 的本地化字符串。
        /// </summary>
        internal static string ObservableObjectCollection_ReadOnly {
            get {
                return ResourceManager.GetString("ObservableObjectCollection_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid maximum drop down height value &apos;{0}&apos;. The value must be greater than or equal to zero. 的本地化字符串。
        /// </summary>
        internal static string Picker_OnMaxDropDownHeightPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Picker_OnMaxDropDownHeightPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid PopupButtonMode value &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Picker_PopupButtonModeNotValid {
            get {
                return ResourceManager.GetString("Picker_PopupButtonModeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value must be larger than or equal to 0. 的本地化字符串。
        /// </summary>
        internal static string Rating_SetItemCount_ItemCountMustBeLargerThanOrEqualToZero {
            get {
                return ResourceManager.GetString("Rating_SetItemCount_ItemCountMustBeLargerThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rating 的本地化字符串。
        /// </summary>
        internal static string RatingAutomationPeer_GetLocalizedControlTypeCore {
            get {
                return ResourceManager.GetString("RatingAutomationPeer_GetLocalizedControlTypeCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value must be null or a number between 0 and 1. 的本地化字符串。
        /// </summary>
        internal static string RatingAutomationPeer_SetValue {
            get {
                return ResourceManager.GetString("RatingAutomationPeer_SetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Star 的本地化字符串。
        /// </summary>
        internal static string RatingItemAutomationPeer_GetLocalizedControlTypeCore {
            get {
                return ResourceManager.GetString("RatingItemAutomationPeer_GetLocalizedControlTypeCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The RoutedPropertyChangingEvent cannot be canceled. 的本地化字符串。
        /// </summary>
        internal static string RoutedPropertyChangingEventArgs_CancelSet_InvalidOperation {
            get {
                return ResourceManager.GetString("RoutedPropertyChangingEventArgs_CancelSet_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spin action is not valid at this moment. 的本地化字符串。
        /// </summary>
        internal static string Spinner_SpinNotValid {
            get {
                return ResourceManager.GetString("Spinner_SpinNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid PopupMinutesInterval &apos;{0}&apos;. The interval can be set to 0 (no interval) to and including 59. 的本地化字符串。
        /// </summary>
        internal static string TimeInput_PopupMinutesInterval_InvalidValue {
            get {
                return ResourceManager.GetString("TimeInput_PopupMinutesInterval_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid PopupSecondsInterval &apos;{0}&apos;.The interval can be set to 0 (no interval) to and including 59. 的本地化字符串。
        /// </summary>
        internal static string TimeInput_PopupSecondsInterval_InvalidValue {
            get {
                return ResourceManager.GetString("TimeInput_PopupSecondsInterval_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot set the PopupProperty in a style. Please use PopupTemplate. 的本地化字符串。
        /// </summary>
        internal static string TimePicker_PopupSetInStyle {
            get {
                return ResourceManager.GetString("TimePicker_PopupSetInStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid PopupTimeSelectionMode for this popup, value &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string TimePicker_PopupTimeSelectionModeNotValid {
            get {
                return ResourceManager.GetString("TimePicker_PopupTimeSelectionModeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot set read-only property TimeHintContent. 的本地化字符串。
        /// </summary>
        internal static string TimeUpDown_OnTimeHintContentChanged {
            get {
                return ResourceManager.GetString("TimeUpDown_OnTimeHintContentChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; is unable to convert &apos;{1}&apos; to &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string TypeConverters_Convert_CannotConvert {
            get {
                return ResourceManager.GetString("TypeConverters_Convert_CannotConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; cannot convert from &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string TypeConverters_ConvertFrom_CannotConvertFromType {
            get {
                return ResourceManager.GetString("TypeConverters_ConvertFrom_CannotConvertFromType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot parse text &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string UpDown_ParseException {
            get {
                return ResourceManager.GetString("UpDown_ParseException", resourceCulture);
            }
        }
    }
}
